# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/voidlogic/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.6494.38/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/voidlogic/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.6494.38/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/voidlogic/CLionProjects/QuantumLatticeRenormalisation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/voidlogic/CLionProjects/QuantumLatticeRenormalisation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/voidlogic/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.6494.38/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/voidlogic/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.6494.38/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/voidlogic/CLionProjects/QuantumLatticeRenormalisation/CMakeFiles /home/voidlogic/CLionProjects/QuantumLatticeRenormalisation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/voidlogic/CLionProjects/QuantumLatticeRenormalisation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_gen_distribution

# Build rule for target.
test_gen_distribution: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_gen_distribution
.PHONY : test_gen_distribution

# fast build rule for target.
test_gen_distribution/fast:
	$(MAKE) -f CMakeFiles/test_gen_distribution.dir/build.make CMakeFiles/test_gen_distribution.dir/build
.PHONY : test_gen_distribution/fast

#=============================================================================
# Target rules for targets named graphsim

# Build rule for target.
graphsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphsim
.PHONY : graphsim

# fast build rule for target.
graphsim/fast:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/build
.PHONY : graphsim/fast

#=============================================================================
# Target rules for targets named QuantumLatticeRenormalisation

# Build rule for target.
QuantumLatticeRenormalisation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QuantumLatticeRenormalisation
.PHONY : QuantumLatticeRenormalisation

# fast build rule for target.
QuantumLatticeRenormalisation/fast:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/build
.PHONY : QuantumLatticeRenormalisation/fast

CandidateLookupTree.o: CandidateLookupTree.cpp.o

.PHONY : CandidateLookupTree.o

# target to build an object file
CandidateLookupTree.cpp.o:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/CandidateLookupTree.cpp.o
.PHONY : CandidateLookupTree.cpp.o

CandidateLookupTree.i: CandidateLookupTree.cpp.i

.PHONY : CandidateLookupTree.i

# target to preprocess a source file
CandidateLookupTree.cpp.i:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/CandidateLookupTree.cpp.i
.PHONY : CandidateLookupTree.cpp.i

CandidateLookupTree.s: CandidateLookupTree.cpp.s

.PHONY : CandidateLookupTree.s

# target to generate assembly for a file
CandidateLookupTree.cpp.s:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/CandidateLookupTree.cpp.s
.PHONY : CandidateLookupTree.cpp.s

GraphRegister2.o: GraphRegister2.cpp.o

.PHONY : GraphRegister2.o

# target to build an object file
GraphRegister2.cpp.o:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/GraphRegister2.cpp.o
.PHONY : GraphRegister2.cpp.o

GraphRegister2.i: GraphRegister2.cpp.i

.PHONY : GraphRegister2.i

# target to preprocess a source file
GraphRegister2.cpp.i:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/GraphRegister2.cpp.i
.PHONY : GraphRegister2.cpp.i

GraphRegister2.s: GraphRegister2.cpp.s

.PHONY : GraphRegister2.s

# target to generate assembly for a file
GraphRegister2.cpp.s:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/GraphRegister2.cpp.s
.PHONY : GraphRegister2.cpp.s

GraphSim/graphsim.o: GraphSim/graphsim.cpp.o

.PHONY : GraphSim/graphsim.o

# target to build an object file
GraphSim/graphsim.cpp.o:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/graphsim.cpp.o
.PHONY : GraphSim/graphsim.cpp.o

GraphSim/graphsim.i: GraphSim/graphsim.cpp.i

.PHONY : GraphSim/graphsim.i

# target to preprocess a source file
GraphSim/graphsim.cpp.i:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/graphsim.cpp.i
.PHONY : GraphSim/graphsim.cpp.i

GraphSim/graphsim.s: GraphSim/graphsim.cpp.s

.PHONY : GraphSim/graphsim.s

# target to generate assembly for a file
GraphSim/graphsim.cpp.s:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/graphsim.cpp.s
.PHONY : GraphSim/graphsim.cpp.s

GraphSim/loccliff.o: GraphSim/loccliff.cpp.o

.PHONY : GraphSim/loccliff.o

# target to build an object file
GraphSim/loccliff.cpp.o:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/loccliff.cpp.o
.PHONY : GraphSim/loccliff.cpp.o

GraphSim/loccliff.i: GraphSim/loccliff.cpp.i

.PHONY : GraphSim/loccliff.i

# target to preprocess a source file
GraphSim/loccliff.cpp.i:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/loccliff.cpp.i
.PHONY : GraphSim/loccliff.cpp.i

GraphSim/loccliff.s: GraphSim/loccliff.cpp.s

.PHONY : GraphSim/loccliff.s

# target to generate assembly for a file
GraphSim/loccliff.cpp.s:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/loccliff.cpp.s
.PHONY : GraphSim/loccliff.cpp.s

GraphSim/stabilizer.o: GraphSim/stabilizer.cpp.o

.PHONY : GraphSim/stabilizer.o

# target to build an object file
GraphSim/stabilizer.cpp.o:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/stabilizer.cpp.o
.PHONY : GraphSim/stabilizer.cpp.o

GraphSim/stabilizer.i: GraphSim/stabilizer.cpp.i

.PHONY : GraphSim/stabilizer.i

# target to preprocess a source file
GraphSim/stabilizer.cpp.i:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/stabilizer.cpp.i
.PHONY : GraphSim/stabilizer.cpp.i

GraphSim/stabilizer.s: GraphSim/stabilizer.cpp.s

.PHONY : GraphSim/stabilizer.s

# target to generate assembly for a file
GraphSim/stabilizer.cpp.s:
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/GraphSim/stabilizer.cpp.s
.PHONY : GraphSim/stabilizer.cpp.s

LatticeDistributionStatistics/test_gen_distribution.o: LatticeDistributionStatistics/test_gen_distribution.cpp.o

.PHONY : LatticeDistributionStatistics/test_gen_distribution.o

# target to build an object file
LatticeDistributionStatistics/test_gen_distribution.cpp.o:
	$(MAKE) -f CMakeFiles/test_gen_distribution.dir/build.make CMakeFiles/test_gen_distribution.dir/LatticeDistributionStatistics/test_gen_distribution.cpp.o
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/LatticeDistributionStatistics/test_gen_distribution.cpp.o
.PHONY : LatticeDistributionStatistics/test_gen_distribution.cpp.o

LatticeDistributionStatistics/test_gen_distribution.i: LatticeDistributionStatistics/test_gen_distribution.cpp.i

.PHONY : LatticeDistributionStatistics/test_gen_distribution.i

# target to preprocess a source file
LatticeDistributionStatistics/test_gen_distribution.cpp.i:
	$(MAKE) -f CMakeFiles/test_gen_distribution.dir/build.make CMakeFiles/test_gen_distribution.dir/LatticeDistributionStatistics/test_gen_distribution.cpp.i
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/LatticeDistributionStatistics/test_gen_distribution.cpp.i
.PHONY : LatticeDistributionStatistics/test_gen_distribution.cpp.i

LatticeDistributionStatistics/test_gen_distribution.s: LatticeDistributionStatistics/test_gen_distribution.cpp.s

.PHONY : LatticeDistributionStatistics/test_gen_distribution.s

# target to generate assembly for a file
LatticeDistributionStatistics/test_gen_distribution.cpp.s:
	$(MAKE) -f CMakeFiles/test_gen_distribution.dir/build.make CMakeFiles/test_gen_distribution.dir/LatticeDistributionStatistics/test_gen_distribution.cpp.s
	$(MAKE) -f CMakeFiles/graphsim.dir/build.make CMakeFiles/graphsim.dir/LatticeDistributionStatistics/test_gen_distribution.cpp.s
.PHONY : LatticeDistributionStatistics/test_gen_distribution.cpp.s

VF2Wrapper.o: VF2Wrapper.cpp.o

.PHONY : VF2Wrapper.o

# target to build an object file
VF2Wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/VF2Wrapper.cpp.o
.PHONY : VF2Wrapper.cpp.o

VF2Wrapper.i: VF2Wrapper.cpp.i

.PHONY : VF2Wrapper.i

# target to preprocess a source file
VF2Wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/VF2Wrapper.cpp.i
.PHONY : VF2Wrapper.cpp.i

VF2Wrapper.s: VF2Wrapper.cpp.s

.PHONY : VF2Wrapper.s

# target to generate assembly for a file
VF2Wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/VF2Wrapper.cpp.s
.PHONY : VF2Wrapper.cpp.s

foliation.o: foliation.cpp.o

.PHONY : foliation.o

# target to build an object file
foliation.cpp.o:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/foliation.cpp.o
.PHONY : foliation.cpp.o

foliation.i: foliation.cpp.i

.PHONY : foliation.i

# target to preprocess a source file
foliation.cpp.i:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/foliation.cpp.i
.PHONY : foliation.cpp.i

foliation.s: foliation.cpp.s

.PHONY : foliation.s

# target to generate assembly for a file
foliation.cpp.s:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/foliation.cpp.s
.PHONY : foliation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/main.cpp.s
.PHONY : main.cpp.s

similarity.o: similarity.cpp.o

.PHONY : similarity.o

# target to build an object file
similarity.cpp.o:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/similarity.cpp.o
.PHONY : similarity.cpp.o

similarity.i: similarity.cpp.i

.PHONY : similarity.i

# target to preprocess a source file
similarity.cpp.i:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/similarity.cpp.i
.PHONY : similarity.cpp.i

similarity.s: similarity.cpp.s

.PHONY : similarity.s

# target to generate assembly for a file
similarity.cpp.s:
	$(MAKE) -f CMakeFiles/QuantumLatticeRenormalisation.dir/build.make CMakeFiles/QuantumLatticeRenormalisation.dir/similarity.cpp.s
.PHONY : similarity.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_gen_distribution"
	@echo "... graphsim"
	@echo "... QuantumLatticeRenormalisation"
	@echo "... CandidateLookupTree.o"
	@echo "... CandidateLookupTree.i"
	@echo "... CandidateLookupTree.s"
	@echo "... GraphRegister2.o"
	@echo "... GraphRegister2.i"
	@echo "... GraphRegister2.s"
	@echo "... GraphSim/graphsim.o"
	@echo "... GraphSim/graphsim.i"
	@echo "... GraphSim/graphsim.s"
	@echo "... GraphSim/loccliff.o"
	@echo "... GraphSim/loccliff.i"
	@echo "... GraphSim/loccliff.s"
	@echo "... GraphSim/stabilizer.o"
	@echo "... GraphSim/stabilizer.i"
	@echo "... GraphSim/stabilizer.s"
	@echo "... LatticeDistributionStatistics/test_gen_distribution.o"
	@echo "... LatticeDistributionStatistics/test_gen_distribution.i"
	@echo "... LatticeDistributionStatistics/test_gen_distribution.s"
	@echo "... VF2Wrapper.o"
	@echo "... VF2Wrapper.i"
	@echo "... VF2Wrapper.s"
	@echo "... foliation.o"
	@echo "... foliation.i"
	@echo "... foliation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... similarity.o"
	@echo "... similarity.i"
	@echo "... similarity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

