//
// Created by voidlogic on 05/08/2020.
//

#ifndef QUANTUMLATTICERENORMALISATION_DIAMONDGRAPH_H
#define QUANTUMLATTICERENORMALISATION_DIAMONDGRAPH_H


class DiamondGraph {

};


#endif //QUANTUMLATTICERENORMALISATION_DIAMONDGRAPH_H
